<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/3_Preparacion_y_Limpieza_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🧹**Métodos de preparación y limpieza de datos**

👉 Luego de cargar nuestro dataset, el primer paso es limpiar los datos, para que podamos confiar en ellos. Aunque puede llegar a ser un proceso tedioso, es una parte **crítica** para lograr hacer un correcto y adecuado análisis de los datos.

✅ Resultado: un dataset limpio, coherente y confiable.

**Objetivos de Aprendizaje**

Al finalizar este notebook, serás capaz de:

1. **Identificar y manejar distintos tipos de problemas** en conjuntos de datos  como duplicados, valores faltantes, tipos de datos incorrectos e inconsistencias de formato.
2. **Aplicar técnicas de limpieza para transformar datos crudos** en un formato listo para el análisis, utilizando Pandas.
3. **Comprender las implicaciones económicas y los sesgos** que pueden surgir de una limpieza de datos deficiente o de decisiones de limpieza sesgadas.
4. **Aplicar buenas prácticas** en proyectos de análisis económico y ciencia de datos.

Imagina que eres un economista del Banco de la República encargado de analizar la inflación en diferentes regiones del país. Recibes un conjunto de datos con precios de productos, pero al revisarlos, notas que algunas entradas tienen precios en diferentes monedas, otras tienen símbolos de moneda ($) que impiden hacer cálculos, y algunas filas están duplicadas o contienen errores evidentes.

Si intentaras calcular la inflación con estos datos sucios, tu resultado sería incorrecto e inútil para la política monetaria. **La limpieza de datos es el proceso de convertir esta "materia prima" defectuosa en un insumo de calidad para que tus modelos económicos y de machine learning sean fiables.** Es similar a la inspección de calidad que se realiza en una fábrica: antes de usar cualquier componente, debes asegurarte de que está en perfectas condiciones.

**Datos crudos Vs Procesados**

![Datos crudos Vs Procesados](https://drive.google.com/uc?id=11i1KhvpeDKMjcxL9rUX7W4pVcjXzz04w)

**Actividad de discusión rápida:** ¿Qué problemas de datos han visto en Excel o en reportes de su carrera?

---

## Importar librerías

In [3]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Mejorar visualización de los dataframes

In [2]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Establecer la ruta de los datasets

In [ ]:
from google.colab import drive, files
drive.mount('/content/drive')

In [1]:
path = 'C:\\Users\\Ferney Reina\\Documents\\Python\\IA_Economia\\2025-segundo-semestre-ia-economia\\datasets'

In [4]:
# Para establecer el directorio de los archivos
os.chdir(path)

---

**NOTA:** CONTROL+K+C COMENTA Y DESCOMENTA CTRL+K+U

---

Como ejemplo, vamos a trabajar con un conjunto de datos de la UNCTAD, el cual trae información de los flujos de inversión extranjera directa en el mundo desde 1970 hasta 2021. Este set de datos ha sido modificado con fines educativos.

## Cargar el dataset

In [27]:
df = pd.read_excel('UNCTAD_2021-FDI.xlsx', skiprows=4)

## Exploración inicial del dataset

In [28]:
df

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,ECONOMY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,...,93.591315,51.533897,119.435106,23.404554,12.970148,20.600976,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Albania,..,..,..,..,..,..,..,..,..,...,1100.671891,1148.891224,1289.689054,1287.966989,1108.159167,1233.917686,Inward,15072022.0,US dollars at current prices in milions,Flow
3,Algeria,80.12,0.6,41.49,51,358,119,187,178.45,135.15,...,1636.299236,1232.341924,1474.589069,1381.812315,1142.640689,869.681819,Inward,15072022.0,US dollars at current prices in milions,Flow
4,Angola,2.4,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,...,-179.517619,-7397.295409,-6456.076413,-4098.478748,-1866.468113,-4150.064316,Inward,15072022.0,US dollars at current prices in milions,Flow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,Yemen,_,_,_,_,_,_,_,_,_,...,0.787,5.601,3.605667,3.331222,..,..,Outward,22072022.0,US dollars at current prices in millions,Flow
431,"Yemen, Democratic",..,..,..,..,..,..,..,..,..,...,_,_,_,_,_,_,Outward,22072022.0,US dollars at current prices in millions,Flow
432,"Yugoslavia, Soc. Fed. Rep. of",..,..,..,..,..,..,..,..,..,...,_,_,_,_,_,_,Outward,22072022.0,US dollars at current prices in millions,Flow
433,Zambia,..,..,..,..,..,..,..,..,..,...,176.719767,-72.04787,45.322767,696.154435,35.434117,-453.376894,Outward,22072022.0,US dollars at current prices in millions,Flow
434,Zimbabwe,..,..,..,..,..,..,..,..,..,...,28.79669,42.231841,26.771877,30.5,44,55,Outward,22072022.0,US dollars at current prices in millions,Flow

In [29]:
df.shape

(435, 57)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 57 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YEAR             435 non-null    object
 1   1970             434 non-null    object
 2   1971             434 non-null    object
 3   1972             434 non-null    object
 4   1973             434 non-null    object
 5   1974             434 non-null    object
 6   1975             434 non-null    object
 7   1976             434 non-null    object
 8   1977             434 non-null    object
 9   1978             434 non-null    object
 10  1979             434 non-null    object
 11  1980             434 non-null    object
 12  1981             434 non-null    object
 13  1982             434 non-null    object
 14  1983             434 non-null    object
 15  1984             434 non-null    object
 16  1985             434 non-null    object
 17  1986             434 non-null    object
 18  1987             434 non-null    object
 19  1988             434 non-null    object
 20  1989             434 non-null    object
 21  1990             434 non-null    object
 22  1991             434 non-null    object
 23  1992             434 non-null    object
 24  1993             434 non-null    object
 25  1994             434 non-null    object
 26  1995             434 non-null    object
 27  1996             434 non-null    object
 28  1997             434 non-null    object
 29  1998             434 non-null    object
 30  1999             434 non-null    object
 31  2000             434 non-null    object
 32  2001             434 non-null    object
 33  2002             434 non-null    object
 34  2003             434 non-null    object
 35  2004             434 non-null    object
 36  2005             434 non-null    object
 37  2006             434 non-null    object
 38  2007             434 non-null    object
 39  2008             434 non-null    object
 40  2009             434 non-null    object
 41  2010             434 non-null    object
 42  2011             434 non-null    object
 43  2012             434 non-null    object
 44  2013             434 non-null    object
 45  2014             434 non-null    object
 46  2015             434 non-null    object
 47  2016             434 non-null    object
 48  2017             434 non-null    object
 49  2018             434 non-null    object
 50  2019             434 non-null    object
 51  2020             434 non-null    object
 52  2021             434 non-null    object
 53  DIRECTION        434 non-null    object
 54  SUBMISSION_DATE  434 non-null    float64
 55  MEASURE          434 non-null    object
 56  MODE             434 non-null    object
dtypes: float64(1), object(56)
memory usage: 193.8+ KB

## Eliminar la primera fila

In [31]:
df.drop(index=0, inplace=True)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
1,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,...,93.591315,51.533897,119.435106,23.404554,12.970148,20.600976,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Albania,..,..,..,..,..,..,..,..,..,...,1100.671891,1148.891224,1289.689054,1287.966989,1108.159167,1233.917686,Inward,15072022.0,US dollars at current prices in milions,Flow
3,Algeria,80.12,0.6,41.49,51,358,119,187,178.45,135.15,...,1636.299236,1232.341924,1474.589069,1381.812315,1142.640689,869.681819,Inward,15072022.0,US dollars at current prices in milions,Flow
4,Angola,2.4,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,...,-179.517619,-7397.295409,-6456.076413,-4098.478748,-1866.468113,-4150.064316,Inward,15072022.0,US dollars at current prices in milions,Flow
5,Anguilla,..,..,..,..,..,..,..,..,..,...,114.837901,97.167478,209.540792,140.221646,60.892553,80.622633,Inward,15072022.0,US dollars at current prices in milions,Flow

## Reiniciar índice para mantener el orden

In [32]:
df.reset_index(inplace=True,drop=True)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,...,93.591315,51.533897,119.435106,23.404554,12.970148,20.600976,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,..,..,..,..,..,..,..,..,..,...,1100.671891,1148.891224,1289.689054,1287.966989,1108.159167,1233.917686,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Algeria,80.12,0.6,41.49,51,358,119,187,178.45,135.15,...,1636.299236,1232.341924,1474.589069,1381.812315,1142.640689,869.681819,Inward,15072022.0,US dollars at current prices in milions,Flow
3,Angola,2.4,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,...,-179.517619,-7397.295409,-6456.076413,-4098.478748,-1866.468113,-4150.064316,Inward,15072022.0,US dollars at current prices in milions,Flow
4,Anguilla,..,..,..,..,..,..,..,..,..,...,114.837901,97.167478,209.540792,140.221646,60.892553,80.622633,Inward,15072022.0,US dollars at current prices in milions,Flow

## Ejercicio: Convertir el valor de la inversión de object a float

In [39]:
# Seleccionar solo las columnas de años para convertir a float
year_cols = ["1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979",
             "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989",
             "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
             "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
             "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
             "2020", "2021"]
df[year_cols] = df[year_cols].replace({'..': np.nan, '_': np.nan, '': np.nan})
df[year_cols] = df[year_cols].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 57 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YEAR             434 non-null    object
 1   1970             148 non-null    float64
 2   1971             151 non-null    float64
 3   1972             161 non-null    float64
 4   1973             167 non-null    float64
 5   1974             173 non-null    float64
 6   1975             177 non-null    float64
 7   1976             186 non-null    float64
 8   1977             193 non-null    float64
 9   1978             196 non-null    float64
 10  1979             199 non-null    float64
 11  1980             213 non-null    float64
 12  1981             217 non-null    float64
 13  1982             224 non-null    float64
 14  1983             228 non-null    float64
 15  1984             230 non-null    float64
 16  1985             239 non-null    float64
 17  1986             244 non-null    float64
 18  1987             253 non-null    float64
 19  1988             257 non-null    float64
 20  1989             262 non-null    float64
 21  1990             275 non-null    float64
 22  1991             275 non-null    float64
 23  1992             297 non-null    float64
 24  1993             309 non-null    float64
 25  1994             312 non-null    float64
 26  1995             315 non-null    float64
 27  1996             322 non-null    float64
 28  1997             324 non-null    float64
 29  1998             324 non-null    float64
 30  1999             327 non-null    float64
 31  2000             327 non-null    float64
 32  2001             334 non-null    float64
 33  2002             338 non-null    float64
 34  2003             341 non-null    float64
 35  2004             345 non-null    float64
 36  2005             347 non-null    float64
 37  2006             346 non-null    float64
 38  2007             351 non-null    float64
 39  2008             353 non-null    float64
 40  2009             352 non-null    float64
 41  2010             356 non-null    float64
 42  2011             362 non-null    float64
 43  2012             364 non-null    float64
 44  2013             364 non-null    float64
 45  2014             371 non-null    float64
 46  2015             374 non-null    float64
 47  2016             377 non-null    float64
 48  2017             376 non-null    float64
 49  2018             375 non-null    float64
 50  2019             376 non-null    float64
 51  2020             372 non-null    float64
 52  2021             371 non-null    float64
 53  DIRECTION        434 non-null    object
 54  SUBMISSION_DATE  434 non-null    float64
 55  MEASURE          434 non-null    object
 56  MODE             434 non-null    object
dtypes: float64(53), object(4)
memory usage: 193.4+ KB

Se logró convertir los datos a números! Ya se pueden realizar operaciones con estos.

In [40]:
df['2020'].mean()

np.float64(5021.3543915973605)

In [41]:
df['2020'].describe()

count       372.000000
mean       5021.354392
std       28418.614336
min     -191397.250746
25%           6.666562
50%         155.059100
75%        2560.595000
max      234919.000000
Name: 2020, dtype: float64

In [42]:
df.describe()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,SUBMISSION_DATE
count,148.000000,151.000000,161.000000,167.000000,173.000000,177.000000,186.000000,193.000000,196.000000,199.000000,...,364.000000,371.000000,374.000000,377.000000,376.000000,375.000000,376.000000,372.000000,371.000000,4.340000e+02
mean,188.259491,190.413779,191.352192,278.122773,281.036811,308.969183,272.671314,287.996346,373.088603,525.024644,...,8633.511979,8011.939369,10889.454924,10088.188475,8934.417568,6671.100809,7326.642282,5021.354392,9242.902349,2.138308e+07
std,690.120073,703.735856,708.972893,1065.866790,1026.820844,1209.740768,1050.126909,1043.231442,1452.861007,2331.104545,...,26069.954496,28737.884925,39774.084285,38761.466240,31369.648198,25012.697949,25736.085723,28418.614336,35875.622461,5.246577e+06
min,-23.000000,-111.440000,-376.000000,-625.910000,-3732.390000,-576.300000,-396.600000,-451.270000,-692.450000,-1270.520000,...,-7120.017424,-151285.932898,-66821.480406,-37605.822070,-27369.776663,-157406.000000,-105806.794166,-191397.250746,-81055.609542,1.507202e+07
25%,3.057500,1.190000,1.560000,1.355000,1.700000,3.000000,2.050000,2.260000,1.992500,1.150000,...,40.741714,28.274541,23.780635,24.245498,17.826705,30.493666,25.248818,6.666562,26.279526,1.582202e+07
50%,18.335000,15.927500,15.200000,13.200000,14.300000,22.560000,11.135000,17.100000,21.070000,17.100000,...,521.250376,410.000000,342.077051,296.700000,348.770874,340.190787,404.500000,155.059100,263.500000,2.207202e+07
75%,93.250000,97.000000,90.430000,89.480000,106.000000,128.000000,90.760000,97.500000,108.615000,127.425000,...,3608.137917,3736.170334,3258.526587,2954.000000,3328.798624,3443.192667,3355.656253,2560.595000,3539.946086,2.507202e+07
max,7590.000000,7618.000000,7747.000000,11353.000000,9052.000000,14244.000000,11949.000000,11400.000000,16225.000000,26493.000000,...,303432.000000,333014.000000,467625.000000,459419.000000,327780.000000,203234.000000,232627.171324,234919.000000,403101.000000,3.007202e+07

## Redondear las cifras de inversión a un decimal

In [43]:
# Redondear el valor de una columna a 1 decimal
df['1970'] = df['1970'].round(1)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.2,0.45,0.15,0.27,NaN,NaN,0.04,-0.24,NaN,...,93.591315,51.533897,119.435106,23.404554,12.970148,20.600976,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100.671891,1148.891224,1289.689054,1287.966989,1108.159167,1233.917686,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Algeria,80.1,0.60,41.49,51.00,358.00,119.00,187.00,178.45,135.15,...,1636.299236,1232.341924,1474.589069,1381.812315,1142.640689,869.681819,Inward,15072022.0,US dollars at current prices in milions,Flow
3,Angola,2.4,1.86,2.16,7.54,6.69,0.05,-1.17,NaN,1.87,...,-179.517619,-7397.295409,-6456.076413,-4098.478748,-1866.468113,-4150.064316,Inward,15072022.0,US dollars at current prices in milions,Flow
4,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,114.837901,97.167478,209.540792,140.221646,60.892553,80.622633,Inward,15072022.0,US dollars at current prices in milions,Flow

In [44]:
# Redondear el valor de todas las columnas del dataframe a 1 decimal
df = df.round(1)
df.head(3)

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.2,0.4,0.2,0.3,NaN,NaN,0.0,-0.2,NaN,...,93.6,51.5,119.4,23.4,13.0,20.6,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1100.7,1148.9,1289.7,1288.0,1108.2,1233.9,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Algeria,80.1,0.6,41.5,51.0,358.0,119.0,187.0,178.4,135.2,...,1636.3,1232.3,1474.6,1381.8,1142.6,869.7,Inward,15072022.0,US dollars at current prices in milions,Flow

## Eliminar columnas innecesarias

### Opción 1

In [45]:
# Vamos a dejar la información solo hasta 2020
df.drop(columns=['2021'], inplace=True)
df.head(3)

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.2,0.4,0.2,0.3,NaN,NaN,0.0,-0.2,NaN,...,169.1,93.6,51.5,119.4,23.4,13.0,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Algeria,80.1,0.6,41.5,51.0,358.0,119.0,187.0,178.4,135.2,...,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6,Inward,15072022.0,US dollars at current prices in milions,Flow

### Opción 2

In [46]:
# Vamos a dejar solo los años de 1980 en adelante
borrar = ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979']
df=df.drop(columns=borrar)
df.head(3)

,YEAR,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,9.0,0.2,0.1,NaN,NaN,NaN,NaN,0.4,NaN,...,169.1,93.6,51.5,119.4,23.4,13.0,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,Inward,15072022.0,US dollars at current prices in milions,Flow
2,Algeria,348.7,13.2,-53.6,0.4,0.8,0.4,5.3,3.7,13.0,...,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6,Inward,15072022.0,US dollars at current prices in milions,Flow

### Opción 3

In [47]:
# En este caso voy a dejar los datos solo desde el año 2000 en adelante
df = df[['YEAR', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', 'DIRECTION',
       'SUBMISSION_DATE', 'MEASURE', 'MODE']]
df.head(2)

,YEAR,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.2,0.7,50.0,57.8,186.9,271.0,238.0,188.7,46.0,...,169.1,93.6,51.5,119.4,23.4,13.0,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,144.3,206.4,133.1,177.1,345.7,264.3,324.4,658.5,974.3,...,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,Inward,15072022.0,US dollars at current prices in milions,Flow

## Cambiar el nombre de una columna

In [48]:
# Vamos a renombrar la columna YEAR
df.rename(columns={"YEAR": "COUNTRY"}, inplace=True)
#df = df.rename(columns={"YEAR": "COUNTRY"})
df.head(2)

,COUNTRY,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.2,0.7,50.0,57.8,186.9,271.0,238.0,188.7,46.0,...,169.1,93.6,51.5,119.4,23.4,13.0,Inward,15072022.0,US dollars at current prices in milions,Flow
1,Albania,144.3,206.4,133.1,177.1,345.7,264.3,324.4,658.5,974.3,...,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,Inward,15072022.0,US dollars at current prices in milions,Flow

## Reorganizar columnas

In [49]:
df.columns

Index(['COUNTRY', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', 'DIRECTION', 'SUBMISSION_DATE',
       'MEASURE', 'MODE'],
      dtype='object')

In [50]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df = df[['COUNTRY', 'DIRECTION', 'SUBMISSION_DATE',
       'MEASURE', 'MODE', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020']]
df.head(2)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Inward,15072022.0,US dollars at current prices in milions,Flow,0.2,0.7,50.0,57.8,186.9,...,57.6,40.9,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0
1,Albania,Inward,15072022.0,US dollars at current prices in milions,Flow,144.3,206.4,133.1,177.1,345.7,...,876.3,855.4,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2

## Procesamiento de Índices

In [51]:
# Volver una columna el índice del df
df = df.set_index('COUNTRY')
df.head()

,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
COUNTRY,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Inward,15072022.0,US dollars at current prices in milions,Flow,0.2,0.7,50.0,57.8,186.9,271.0,...,57.6,40.9,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0
Albania,Inward,15072022.0,US dollars at current prices in milions,Flow,144.3,206.4,133.1,177.1,345.7,264.3,...,876.3,855.4,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2
Algeria,Inward,15072022.0,US dollars at current prices in milions,Flow,280.1,1113.1,1065.0,637.9,884.7,1145.6,...,2580.6,1499.4,1696.9,1506.7,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6
Angola,Inward,15072022.0,US dollars at current prices in milions,Flow,878.6,2145.5,1743.5,3577.0,2197.2,-1303.8,...,-3023.8,-1464.6,-7120.0,3657.5,10028.2,-179.5,-7397.3,-6456.1,-4098.5,-1866.5
Anguilla,Inward,15072022.0,US dollars at current prices in milions,Flow,39.7,29.6,33.2,29.4,86.7,117.3,...,38.9,43.5,42.1,75.4,82.9,114.8,97.2,209.5,140.2,60.9

In [52]:
# Convertir en columna el índice del df
df = df.reset_index()
df.head()

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Inward,15072022.0,US dollars at current prices in milions,Flow,0.2,0.7,50.0,57.8,186.9,...,57.6,40.9,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0
1,Albania,Inward,15072022.0,US dollars at current prices in milions,Flow,144.3,206.4,133.1,177.1,345.7,...,876.3,855.4,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2
2,Algeria,Inward,15072022.0,US dollars at current prices in milions,Flow,280.1,1113.1,1065.0,637.9,884.7,...,2580.6,1499.4,1696.9,1506.7,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6
3,Angola,Inward,15072022.0,US dollars at current prices in milions,Flow,878.6,2145.5,1743.5,3577.0,2197.2,...,-3023.8,-1464.6,-7120.0,3657.5,10028.2,-179.5,-7397.3,-6456.1,-4098.5,-1866.5
4,Anguilla,Inward,15072022.0,US dollars at current prices in milions,Flow,39.7,29.6,33.2,29.4,86.7,...,38.9,43.5,42.1,75.4,82.9,114.8,97.2,209.5,140.2,60.9

## Revisar y ajustar las variables categóricas

### Direction

In [53]:
df['DIRECTION'].unique()

array(['Inward', 'Inward  ', 'Outward', '00000Outward'], dtype=object)

In [54]:
# Para borrar los espacios en blanco al principio y al final del string
df['DIRECTION']=df['DIRECTION'].str.strip()
df['DIRECTION'].unique()

array(['Inward', 'Outward', '00000Outward'], dtype=object)

In [55]:
# Se quitan los ceros del principio del string
df['DIRECTION'] = df['DIRECTION'].str.lstrip('00000')
df['DIRECTION'].unique()

array(['Inward', 'Outward'], dtype=object)

In [56]:
df['DIRECTION'] = df['DIRECTION'].str.upper()
df['DIRECTION'].unique()

array(['INWARD', 'OUTWARD'], dtype=object)

### Measure

In [57]:
df['MEASURE'].unique()

array(['US dollars at current prices in milions',
       'US dollars at current prices in millions'], dtype=object)

In [58]:
df['MEASURE'] = df['MEASURE'].replace({"US dollars at current prices in milions": "US dollars at current prices in millions"})
df['MEASURE'].unique()

array(['US dollars at current prices in millions'], dtype=object)

In [59]:
df['MEASURE'] = df['MEASURE'].str.upper()
df['MEASURE'].unique()

array(['US DOLLARS AT CURRENT PRICES IN MILLIONS'], dtype=object)

In [60]:
# Dividir en dos partes el string
df['CURRENCY'] = df['MEASURE'].str.split('AT',expand=True)[0]
df['MEASURE_2'] = df['MEASURE'].str.split('AT',expand=True)[1]
df.head(3)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,...,2013,2014,2015,2016,2017,2018,2019,2020,CURRENCY,MEASURE_2
0,Afghanistan,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,0.2,0.7,50.0,57.8,186.9,...,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0,US DOLLARS,CURRENT PRICES IN MILLIONS
1,Albania,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,144.3,206.4,133.1,177.1,345.7,...,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,US DOLLARS,CURRENT PRICES IN MILLIONS
2,Algeria,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,280.1,1113.1,1065.0,637.9,884.7,...,1696.9,1506.7,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6,US DOLLARS,CURRENT PRICES IN MILLIONS

In [61]:
df['PRICE_TYPE'] = df['MEASURE_2'].str.split('IN',expand=True)[0]
df['UNIT'] = df['MEASURE_2'].str.split('IN',expand=True)[1]
df.head(3)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,CURRENCY,MEASURE_2,PRICE_TYPE,UNIT
0,Afghanistan,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,0.2,0.7,50.0,57.8,186.9,...,169.1,93.6,51.5,119.4,23.4,13.0,US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS
1,Albania,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,144.3,206.4,133.1,177.1,345.7,...,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS
2,Algeria,INWARD,15072022.0,US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,280.1,1113.1,1065.0,637.9,884.7,...,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6,US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS

In [62]:
df.columns

Index(['COUNTRY', 'DIRECTION', 'SUBMISSION_DATE', 'MEASURE', 'MODE', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', 'CURRENCY', 'MEASURE_2', 'PRICE_TYPE', 'UNIT'],
      dtype='object')

In [63]:
# Eliminar 'MEASURE' y 'MEASURE_2' y reorganizar columnas
df = df[['COUNTRY', 'MODE', 'DIRECTION', 'CURRENCY', 'UNIT', 'PRICE_TYPE', 'SUBMISSION_DATE', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020']]
df.head(3)

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,0.2,0.7,50.0,...,57.6,40.9,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0
1,Albania,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,144.3,206.4,133.1,...,876.3,855.4,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2
2,Algeria,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,280.1,1113.1,1065.0,...,2580.6,1499.4,1696.9,1506.7,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6

### Mode

In [64]:
df['MODE'].unique()

array(['Flow', "Flow'''"], dtype=object)

In [65]:
# Se quitan las comillas del final del string
df['MODE'] = df['MODE'].str.rstrip("'''")
df['MODE'].unique()

array(['Flow'], dtype=object)

In [66]:
df['MODE'] = df['MODE'].str.upper()
df['MODE'].unique()

array(['FLOW'], dtype=object)

In [67]:
# Contar el número de caracteres
df["num_caracteres"] = df["MODE"].str.len()
df.head()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,num_caracteres
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,0.2,0.7,50.0,...,40.9,48.3,43.0,169.1,93.6,51.5,119.4,23.4,13.0,4
1,Albania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,144.3,206.4,133.1,...,855.4,1265.9,1111.4,945.7,1100.7,1148.9,1289.7,1288.0,1108.2,4
2,Algeria,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,280.1,1113.1,1065.0,...,1499.4,1696.9,1506.7,-584.5,1636.3,1232.3,1474.6,1381.8,1142.6,4
3,Angola,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,878.6,2145.5,1743.5,...,-1464.6,-7120.0,3657.5,10028.2,-179.5,-7397.3,-6456.1,-4098.5,-1866.5,4
4,Anguilla,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,15072022.0,39.7,29.6,33.2,...,43.5,42.1,75.4,82.9,114.8,97.2,209.5,140.2,60.9,4

In [68]:
df["num_caracteres"].unique()

array([4])

In [69]:
df.drop(columns=['num_caracteres'], inplace=True)

## Convertir a tipo category

Convertir variables categóricas a tipo category en pandas es una muy buena práctica en ciencia de datos, y tiene varias ventajas importantes:
- Una columna categórica se almacena como códigos numéricos internos en lugar de cadenas de texto repetidas. Esto reduce muchísimo el uso de memoria, sobre todo cuando tienes miles de filas con pocos valores distintos.
- Operaciones como groupby(), value_counts(), merge() son más rápidas en columnas categóricas porque pandas trabaja con los códigos internos (números) en vez de cadenas de texto largas.
- Preparación para Machine Learning: La mayoría de algoritmos no trabajan directamente con strings. Usar category es el primer paso para luego aplicar OneHotEncoding o LabelEncoding fácilmente.
- Permite diferenciar variables que son realmente categóricas de las que son texto libre. Ejemplo: "Bogotá", "Medellín", "Cali" son categorías (ciudades), no simples cadenas de texto. En un directorio de empresas, la columna de razón social no sería categórica porque cada fila tiene un valor diferente.

In [ ]:
categorias = ['DIRECTION', 'MODE', 'CURRENCY', 'PRICE_TYPE', 'UNIT']
for categoria in categorias:
  df[categoria] = df[categoria].astype('category')
df.info()

## Revisar y ajustar las variables tipo fecha

Cambiar una columna de string, int o float a datetime tiene las siguientes ventajas:

1. Permite aplicar operaciones de calendario como:
- df["fecha"].dt.year      # año
- df["fecha"].dt.month     # mes
- df["fecha"].dt.day       # día

2. Permite comparaciones y filtros más fáciles. Ejemplo: seleccionar datos de 2023 en adelante.

  df[df["fecha"] >= "2023-01-01"]

  Si fueran strings, hacer este filtro sería muy complicado y propenso a errores.

3. Permite realizar operaciones matemáticas con fechas. Puedes calcular diferencias en días, semanas o meses:

  (df["fecha"].max() - df["fecha"].min()).days

4. Puedes ordenar la serie en orden cronológico.

In [ ]:
# Pasar la columna a formato fecha
df['SUBMISSION_DATE'] = pd.to_datetime(df['SUBMISSION_DATE'], format="%d%m%Y")
df.info()

In [ ]:
df.head()

In [ ]:
# Crear una nueva columna que diga solamente el día de envío de la información
df['DIA'] = df["SUBMISSION_DATE"].dt.day
df.sample(5)

In [ ]:
df.drop(columns=['DIA'], inplace=True)

In [ ]:
# Filtrar los registros que se enviaron después del 22 de julio de 2022
df[df["SUBMISSION_DATE"] > "2022-07-22"]

In [ ]:
# Para saber el número de días de envío de información que cubre el dataset
(df["SUBMISSION_DATE"].max() - df["SUBMISSION_DATE"].min()).days

In [ ]:
# Ver el dataset en orden cronológico
df.sort_values(by='SUBMISSION_DATE')

## Duplicados

Puede generar un sesgo por sobrevaloración de una observación.

### Detectar duplicados

In [ ]:
# Encontrar filas con todos sus valores duplicados (ver sólo el primer valor repetido)
df[df.duplicated()]

In [ ]:
# Encontrar filas con todos sus valores duplicados (ver todos los valores repetidos)
df[df.duplicated(keep=False)]

In [ ]:
# Encontrar duplicados en ciertas columnas, ver todos los valores repetidos
df[df.duplicated(subset='COUNTRY', keep=False)]

In [ ]:
# Ver duplicados en varias columnas al tiempo
df[df.duplicated(subset=['COUNTRY','MODE', 'DIRECTION'], keep=False)]

### Ver la cantidad de duplicados que existen

In [ ]:
# En general
df.duplicated().sum()

In [ ]:
# En una columna específica
df['COUNTRY'].duplicated().sum()

In [ ]:
# En varias columnas
df.duplicated(subset=['COUNTRY','MODE', 'DIRECTION']).sum()

### Eliminar duplicados

In [ ]:
# Eliminar filas con todos sus valores duplicados, conservando sólo el primer registro
df.drop_duplicates(keep='first', inplace=True)

In [ ]:
df.duplicated().sum()

In [ ]:
# Eliminar filas con todos sus valores duplicados, conservando sólo el último registro
# df.drop_duplicates(keep='last', inplace=True)

In [ ]:
# Borrar duplicados revisando solo una columna y dejando el último dato que encuentre
# df = df.drop_duplicates(subset="COUNTRY", keep="last")

## Valores faltantes

Implica perdida de información que puede ser muy relevante para el análisis.

### Detectar valores faltantes

In [ ]:
len(df)

In [ ]:
# Ver la cantidad de valores nulos en cada columna
df.isna().sum()

In [ ]:
# Para filtrar los nulos de una columna
df[df['2000'].isna()]

In [ ]:
# Para filtrar los nulos de varias columnas al tiempo
df[df['2000'].isna() & df['2001'].isna()]

In [ ]:
df[df['2000'].isna() | df['2020'].isna()]

### Imputar valores faltantes

La elección del método no es trivial y debe basarse en el conocimiento del problema. Imputar con la media podría subestimar la variabilidad de un mercado, mientras que eliminar datos podría generar un sesgo de selección.

### Eliminar filas con valores faltantes

👉 Útil si los faltantes son muy pocos o irrelevantes.

In [ ]:
len(df)

In [ ]:
# Borrar la fila si hay nulos en ciertas columnas
df_2 = df.dropna(subset=['2020'], how='all')
len(df_2)

In [ ]:
df_2.isna().sum()

In [ ]:
# Borrar la fila si hay nulos en ciertas columnas
df_3 = df.dropna(subset=['2018', '2019', '2020'], how='all')
len(df_3)

In [ ]:
df_3.isna().sum()

In [ ]:
# Borrar todas las filas o registros que tienen datos faltantes en el dataset
df_4 = df.dropna()
len(df_4)

In [ ]:
df_4.isna().sum()

#### Reemplazar todos los faltantes por un valor constante

👉 Se usa cuando un valor por defecto tiene sentido (ej. "No aplica", 0 para exportaciones).

In [ ]:
# Llenar los valores nulos con cero
df['2000'] = df['2000'].fillna(0)
df.tail()

In [ ]:
# Llenar los valores nulos con un string
df['2001'] = df['2001'].fillna('No aplica')
df.tail()

#### Imputación con estadísticas de la columna

👉 Muy usado en economía. Por ejemplo, la media/mediana para ingresos.

In [ ]:
# Llenar los valores nulos con la media de la columna
df['2002'] = df['2002'].fillna(df['2002'].mean())
df.tail()

#### Imputación con valores vecinos

👉 Muy útil en series de tiempo (ejemplo: inflación mensual, PIB trimestral).

##### Forward fill (ffill): usa el último valor válido anterior

In [ ]:
df["2003"].fillna(method="ffill", inplace=True)
df.tail()

##### Backward fill (bfill): usa el siguiente valor válido

In [ ]:
df["2004"].fillna(method="bfill", inplace=True)
df.tail()

#### Interpolación

Calcula valores intermedios automáticamente

👉 Útil en datos económicos continuos, como tasas de crecimiento. Útil en series de tiempo.

In [ ]:
df["2005"].interpolate(method="linear", inplace=True)
df.tail()

#### Modelos predictivos (Machine Learning)

Usa algoritmos para predecir los valores faltantes. Por ejemplo:

- KNN Imputer (usa vecinos más cercanos).

- Regresión (predice usando otras variables).

##### 📌  KNNImputer (Imputación con Vecinos Más Cercanos)

Busca observaciones parecidas (vecinos) usando las demás variables del dataset.

Si una observación tiene un dato faltante, se fija en los valores de esos vecinos más cercanos.

Rellena el valor faltante con el promedio de los vecinos.

* Ejemplo:

Imagina que falta el valor de la inflación de Colombia, pero sí tenemos su PIB. El KNNImputer busca países con PIB similar (como Chile o Perú), y usa sus valores de inflación para calcular un promedio y rellenar el dato faltante de Colombia.

👉 Cosas a tener en cuenta:

- Solo funciona con variables numéricas.

- Conviene escalar o normalizar las variables antes, porque si una está en millones (PIB) y otra en %, dominará la distancia.

- El valor que se asigna es la media de los vecinos (aunque también podrías modificarlo para usar la mediana).

In [ ]:
from sklearn.impute import KNNImputer
import numpy as np

In [ ]:
imputer = KNNImputer(n_neighbors=3)
df[["2020"]] = imputer.fit_transform(df[["2020"]])
df.tail()